FROM python:3.9
WORKDIR /app
COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt
COPY ./backend/app ./app
COPY ./backend/tests ./tests
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]