name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Dump DOT_ENV secret to .env file
      - name: Create .env from secret
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
          echo "Created .env from DOT_ENV secret"
          
      # Build backend_test image
      - name: Build backend_test image
        run: |
          docker compose build backend_test

      # Start db_test container
      - name: Start db_test
        run: |
          docker compose  up -d db_test
          sleep 5  # Give db_test time to start

      # Run backend tests
      - name: Run Backend Tests
        run: |
          docker compose run --rm backend_test

      # Stop db_test container
      - name: Stop db_test
        if: always()  # Run even if tests fail
        run: |
          docker compose stop db_test
          docker compose down