name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    #   # Install Docker Compose
    #   - name: Install Docker Compose
    #     run: |
    #       sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #       sudo chmod +x /usr/local/bin/docker-compose
    #       docker-compose --version

      # Build backend_test image
      - name: Build backend_test image
        run: |
          docker compose build backend_test

      # Start db_test container
      - name: Start db_test
        run: |
          docker compose  up -d db_test
          sleep 5  # Give db_test time to start

      # Run backend tests
      - name: Run Backend Tests
        run: |
          docker compose run --rm backend_test

      # Stop db_test container
      - name: Stop db_test
        if: always()  # Run even if tests fail
        run: |
          docker compose stop db_test
          docker compose down