name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d db_test
          sleep 5  # Give db_test time to start

      # Run backend tests
      - name: Run Backend Tests
        run: |
          docker-compose -f docker-compose.yml run --rm backend_test

      # Stop db_test container
      - name: Stop db_test
        if: always()  # Run even if tests fail
        run: |
          docker-compose -f docker-compose.yml stop db_test